configuration:
    - Debug
    - Release

platform:
    - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      generator: "Unix Makefiles"
    
matrix:
    fast_finish: true
  
before_build:
  - mkdir build
  - cd build

build_script:
    - ps: |-
        cmake .. -G "$env:generator" -DCMAKE_INSTALL_PREFIX="../install"