configuration:
    - Debug
    - Release

platform:
    - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      generator: "Unix Makefiles"
    
matrix:
    fast_finish: false

init:
    - pip install conan
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 


# Prefix command with cmd: to run it on Windows image only:
# Prefix command with sh: to run it on Linux image only:
# Do not prefix command to run it on both Windows and Linux. You have to make sure the command is good for both Windows batch files and Bash:
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
before_build:
    - mkdir build
    - cd build
    - conan install ..

build_script:
    - cmd: |-
        echo %generator% - %configuration%
        cmake .. -G "%generator%" -DCMAKE_INSTALL_PREFIX="../install"
        cmake --build . --target INSTALL --config "%configuration%"
    - sh: |-
        echo $generator - $configuration
        cmake .. -G "$generator" -DCMAKE_INSTALL_PREFIX="../install"
        cmake --build . --target install --config "$configuration"
    
# testing
test_script:
    - ctest

# installing
artifacts:
    - path: install
      name: pkgHello
      type: zip
