configuration:
    - Debug
    - Release

platform:
    - x64

image: 
    - Visual Studio 2017
    - Ubuntu

init:
- cmd: set generator="Visual Studio 15 2017 Win64"
- sh: export generator="Unix Makefiles"
    
matrix:
  fast_finish: false

# Prefix command with cmd: to run it on Windows image only:
# Prefix command with sh: to run it on Linux image only:
# Do not prefix command to run it on both Windows and Linux. You have to make sure the command is good for both Windows batch files and Bash:
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
before_build:
    - mkdir build
    - cd build

build_script:
    - cmake .. -G %generator% -DCMAKE_INSTALL_PREFIX="../install"
    - cmake --build . --target INSTALL --config %configuration%

## installing
artifacts:
    - path: install
      name: pkgHello
      type: zip
