configuration:
    - Debug
    - Release

image: Visual Studio 2017


before_build:
  - cmd: |-
      mkdir build
      cd build
build_script:
    - cmd: |-
        cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="../install"
        cmake --build . --target INSTALL --config %configuration%

## installing
artifacts:
    - path: install
      name: pkgHello
      type: zip