configuration:
    - Debug
    - Release

platform:
    - x64

image: 
    - Visual Studio 2017
    - Ubuntu

init:
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu" ( set generator="Unix Makefiles")
    
matrix:
  fast_finish: true

before_build:
    - cmd: |-
        mkdir build
        cd build
build_script:
    - cmd: |-
        cmake .. -G %generator% -DCMAKE_INSTALL_PREFIX="../install"
        cmake --build . --target INSTALL --config %configuration%

## installing
artifacts:
    - path: install
      name: pkgHello
      type: zip
