configuration:
    - Debug
    - Release

platform:
    - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      GENERATOR: "Unix Makefiles"
  
# fix the init-problem
init: 
  - cmd: pip install conan
  - sh: sudo pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 

before_build:
  - mkdir build
  - cd build
  - cmd: conan install .. -s build_type="$env:CONFIGURATION"
  - sh: conan install .. -s build_type="$env:CONFIGURATION" -s compiler.libcxx=libstdc++11

build_script:
  - ps: cmake .. -G "$env:GENERATOR" -DCMAKE_INSTALL_PREFIX="../install"
  - ps: cmake --build . --target install --config "$env:CONFIGURATION" --parallel 4

test_script:
  - ps: ctest --build-config "$env:CONFIGURATION" -VV
