name: Clang-tidy runner

on: [push, pull_request]

jobs:
  build:
    name: Clang-Tidy Runner
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan profile new default --detect
    - name: Display versions
      run: |
        cmake --version | head -n 1
        gcc --version | head -n 1
        conan --version | head -n 1
        conan profile show default
        cat /etc/lsb-release | grep "DISTRIB_DESCRIPTION"
        clang-tidy --version
    - name: Setting up remotes
      run: conan remote add catch2 https://api.bintray.com/conan/catchorg/Catch2
    - name: install conan dependencies
      run: conan install . -if build -s compiler.libcxx=libstdc++11 -s build_type=Release
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: clang-tidy
      run: |
        cd build 
        python3 /usr/bin/run-clang-tidy -checks="*"
