name: Clang-tidy runner

on: [push, pull_request]

jobs:
  build:
    name: Clang-Tidy Runner
    runs-on: ubuntu-18.04

    steps:
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Dispay clang-tidy version
        run: clang-tidy --version
      
