name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    name: Builder on ${{ matrix.os }} and ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan profile new default --detect
    - name: Display versions
      run: |
        cmake --version | head -n 1
        gcc --version | head -n 1
        conan --version | head -n 1
        conan profile show default
        cat /etc/lsb-release
    - name: Setting up remotes
      run: conan remote add catch2 https://api.bintray.com/conan/catchorg/Catch2
    - name: install conan dependencies
      run: conan install . -if build -s compiler.libcxx=libstdc++11 -s build_type=${{matrix.build_type}}
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure
