name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup pyhton
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
    - name: install conan dependencies
      run: conan install . -if build -s compiler.libcxx=libstdc++11
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure
