name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
    - name: install conan dependencies
      run: conan install . -if build
    - name: cmake
      run: cmake -S . -B build -DCMAKE_CONFIGURATION_TYPES=Release
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure
