name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Builder on ${{ matrix.build_type }}
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
    - name: Display versions
      run: |
        cmake --version | head -n 1
        conan --version | head -n 1
    - name: Setting up remotes
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: install conan dependencies
      run: conan install . -if build -s build_type=${{matrix.build_type}} -s compiler.version=15
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: build
      run: cmake --build build --config ${{matrix.build_type}} --parallel 10
    - name: test
      run: | 
        cd build
        ctest -C ${{matrix.build_type}} -j 10 --output-on-failure
